#version 450

layout(constant_id = 0) const uint c_MaxDescriptorSetsAllowed = 8;

layout(set = 0, binding = 0) uniform sampler2D _FBY_u_BloomImageSampler;
layout(set = 0, binding = 1, rgba16f) uniform image2D _FBY_u_BloomImages[c_MaxDescriptorSetsAllowed];
layout(set = 1, binding = 0, rgba16f) uniform image2D _FBY_u_TargetImage;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#define BLOOM_STAGE_PREFILTER 0
#define BLOOM_STAGE_DOWNSAMPLE 1
#define BLOOM_STAGE_UPSAMPLE 2
#define BLOOM_STAGE_COMPOSITING 3

#include "Include/HDRCommon.glsl"

const float Epsilon = 1.0e-4;

layout(push_constant) uniform BloomSettings {
    float Threshold, Knee, SpreadScale;
    uint BloomStage;
    uint InputIndex, OutputIndex, MipOffset;
} u_BloomSettings;

vec4 QuadraticThreshold(vec4 color, float threshold, vec3 curve) 
{
    float brightness = max(max(color.r, color.g), color.b);
    float rq = clamp(brightness - curve.x, 0.0, curve.y);
    rq = (rq * rq) * curve.z;
    color *= max(rq, brightness - threshold) / max(brightness, Epsilon);
    return color;
}

vec4 Prefilter(vec4 color, vec2 uv, vec4 params)
{
    float clampValue = 20.0f;
    color = min(vec4(clampValue), color);
    color = QuadraticThreshold(color, params.x, params.yzw);
    return color;
}

vec3 DownsampleBox13_Prefilter()
{
	ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

	// Center
	vec3 A = imageLoad(_FBY_u_TargetImage, pixelCoord).rgb;

	// Inner Box
	vec3 B = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2(-1, -1)).rgb;
	vec3 C = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2(-1,  1)).rgb;
	vec3 D = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2( 1,  1)).rgb;
	vec3 E = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2( 1, -1)).rgb;

	vec3 F = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2(-2, -2)).rgb;
	vec3 G = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2(-2,  0)).rgb;
	vec3 H = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2( 0,  2)).rgb;
	vec3 I = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2( 2,  2)).rgb;
	vec3 J = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2( 2,  2)).rgb;
	vec3 K = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2( 2,  0)).rgb;
	vec3 L = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2(-2, -2)).rgb;
	vec3 M = imageLoad(_FBY_u_TargetImage, pixelCoord + ivec2( 0, -2)).rgb;

	vec3 result = vec3(0.0);
	// Inner Box
	result += (B + C + D + E) * 0.5;
	// Bottom-left Box
	result += (F + G + A + M) * 0.125;
	// Top-left Box
	result += (G + H + I + A) * 0.125;
	// Top-right Box
	result += (A + I + J + K) * 0.125;
	// Bottom-right Box
	result += (M + A + K + L) * 0.125;

	// 4 samples each
	result *= 0.25f;

	return result;
}

vec3 DownsampleBox13(sampler2D tex, float lod, vec2 uv, vec2 texelSize)
{
    // Center
    vec3 A = textureLod(tex, uv, lod).rgb;

    texelSize *= 0.5f;// Sample from center of texels

    // Inner box
    vec3 B = textureLod(tex, uv + texelSize * vec2(-1.0f, -1.0f), lod).rgb;
    vec3 C = textureLod(tex, uv + texelSize * vec2(-1.0f, 1.0f), lod).rgb;
    vec3 D = textureLod(tex, uv + texelSize * vec2(1.0f, 1.0f), lod).rgb;
    vec3 E = textureLod(tex, uv + texelSize * vec2(1.0f, -1.0f), lod).rgb;

    // Outer box
    vec3 F = textureLod(tex, uv + texelSize * vec2(-2.0f, -2.0f), lod).rgb;
    vec3 G = textureLod(tex, uv + texelSize * vec2(-2.0f, 0.0f), lod).rgb;
    vec3 H = textureLod(tex, uv + texelSize * vec2(0.0f, 2.0f), lod).rgb;
    vec3 I = textureLod(tex, uv + texelSize * vec2(2.0f, 2.0f), lod).rgb;
    vec3 J = textureLod(tex, uv + texelSize * vec2(2.0f, 2.0f), lod).rgb;
    vec3 K = textureLod(tex, uv + texelSize * vec2(2.0f, 0.0f), lod).rgb;
    vec3 L = textureLod(tex, uv + texelSize * vec2(-2.0f, -2.0f), lod).rgb;
    vec3 M = textureLod(tex, uv + texelSize * vec2(0.0f, -2.0f), lod).rgb;

    // Weights
    vec3 result = vec3(0.0);
    // Inner box
    result += (B + C + D + E) * 0.5f;
    // Bottom-left box
    result += (F + G + A + M) * 0.125f;
    // Top-left box
    result += (G + H + I + A) * 0.125f;
    // Top-right box
    result += (A + I + J + K) * 0.125f;
    // Bottom-right box
    result += (M + A + K + L) * 0.125f;

    // 4 samples each
    result *= 0.25f;

    return result;
}

vec3 UpsampleTent9(sampler2D tex, float lod, vec2 uv, vec2 texelSize, float radius)
{
    vec4 offset = texelSize.xyxy * vec4(1.0f, 1.0f, -1.0f, 0.0f) * radius;

    // Center
    vec3 result = textureLod(tex, uv, lod).rgb * 4.0f;

    result += textureLod(tex, uv - offset.xy, lod).rgb;
    result += textureLod(tex, uv - offset.wy, lod).rgb * 2.0;
    result += textureLod(tex, uv - offset.zy, lod).rgb;

    result += textureLod(tex, uv + offset.zw, lod).rgb * 2.0;
    result += textureLod(tex, uv + offset.xw, lod).rgb * 2.0;

    result += textureLod(tex, uv + offset.zy, lod).rgb;
    result += textureLod(tex, uv + offset.wy, lod).rgb * 2.0;
    result += textureLod(tex, uv + offset.xy, lod).rgb;

    return result * (1.0f / 16.0f);
}

void main()
{
	// (x) threshold, (y) threshold - knee, (z) knee * 2, (w) 0.25 / knee
	const vec4 params = vec4(u_BloomSettings.Threshold, u_BloomSettings.Threshold - u_BloomSettings.Knee, u_BloomSettings.Knee * 2.0, 0.25 / u_BloomSettings.Knee);

	const vec2 imgSize = vec2(imageSize(_FBY_u_BloomImages[u_BloomSettings.OutputIndex]));
	vec2 textureCoords = gl_GlobalInvocationID.xy / imgSize;
	textureCoords += (1.0 / imgSize) * 0.5;

	const vec2 texSize = vec2(textureSize(_FBY_u_BloomImageSampler, int(u_BloomSettings.InputIndex + u_BloomSettings.MipOffset)));

	vec4 color = vec4(0, 0, 0, 1);

	if (u_BloomSettings.BloomStage == BLOOM_STAGE_PREFILTER)
	{
		color.rgb = DownsampleBox13_Prefilter();
		color = Prefilter(color, textureCoords, params);
		color.a = 1.0;
	}
	else if (u_BloomSettings.BloomStage == BLOOM_STAGE_DOWNSAMPLE)
	{
		color.rgb = DownsampleBox13(_FBY_u_BloomImageSampler, u_BloomSettings.InputIndex + u_BloomSettings.MipOffset, textureCoords, 1.0 / texSize);
	}
	else if (u_BloomSettings.BloomStage == BLOOM_STAGE_UPSAMPLE)
	{
		const vec3 upsampled = UpsampleTent9(_FBY_u_BloomImageSampler, u_BloomSettings.InputIndex + u_BloomSettings.MipOffset, textureCoords, 1.0 / texSize, u_BloomSettings.SpreadScale);
		const vec3 existing = textureLod(_FBY_u_BloomImageSampler, textureCoords, int(u_BloomSettings.OutputIndex + u_BloomSettings.MipOffset)).rgb;
		color.rgb = existing + upsampled;
	}
	else if (u_BloomSettings.BloomStage == BLOOM_STAGE_COMPOSITING)
	{
		const vec3 upsampled = UpsampleTent9(_FBY_u_BloomImageSampler, u_BloomSettings.InputIndex + u_BloomSettings.MipOffset, textureCoords, 1.0 / texSize, u_BloomSettings.SpreadScale);
		const vec3 existing = textureLod(_FBY_u_BloomImageSampler, textureCoords, int(u_BloomSettings.OutputIndex + u_BloomSettings.MipOffset)).rgb;
		const vec4 original = imageLoad(_FBY_u_TargetImage, ivec2(gl_GlobalInvocationID.xy));

		color.rgb = existing + upsampled + original.rgb;
		color.a = original.a;
	}

	if (u_BloomSettings.BloomStage == BLOOM_STAGE_COMPOSITING)
		imageStore(_FBY_u_TargetImage, ivec2(gl_GlobalInvocationID.xy), color);
	else
		imageStore(_FBY_u_BloomImages[u_BloomSettings.OutputIndex], ivec2(gl_GlobalInvocationID.xy), color);
}
