# Following code is generated by the generate_project.py script

set(PHYSX_INCLUDE_DIR "${FBY_SOURCE_DIR}/Flameberry/vendor/PhysX/physx/include")
set(PHYSX_CHECKED_LIB_DIRECTORY "${FBY_SOURCE_DIR}/Flameberry/vendor/PhysX/physx/bin/mac.x86_64/checked")
set(PHYSX_RELEASE_LIB_DIRECTORY "${FBY_SOURCE_DIR}/Flameberry/vendor/PhysX/physx/bin/mac.x86_64/release")
set(PHYSX_COMPILE_DEFINITIONS NDEBUG)
